# Generated by Django 5.1.6 on 2025-03-04 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('longitude', models.FloatField(default=104.07, verbose_name='经度')),
                ('latitude', models.FloatField(default=30.67, verbose_name='纬度')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('category', models.CharField(choices=[('古镇', '古镇'), ('自然风光', '自然风光'), ('历史文化', '历史文化'), ('现代建筑', '现代建筑')], max_length=50, verbose_name='分类')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='开放时间')),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='门票价格')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_spots', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
        ),
    ]
