# Generated by Django 5.1.6 on 2025-03-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenicspot',
            name='category',
            field=models.CharField(choices=[('历史文化', '历史文化'), ('美食探索', '美食探索'), ('自然风光', '自然风光'), ('购物娱乐', '购物娱乐'), ('艺术展馆', '艺术展馆'), ('古镇民俗', '古镇民俗'), ('主题乐园', '主题乐园'), ('休闲度假', '休闲度假'), ('宗教文化', '宗教文化'), ('城市景观', '城市景观'), ('其他', '其他')], max_length=50, verbose_name='分类'),
        ),
    ]
